<?php

//================================================
// Settings:

$dbName = "demo";
$dbUser = "root";
$dbPass = "";
$dbServer = "127.0.0.1";
$tableName = "user";

//================================================

$fixtureOutput = "<?php\n";
$fixtureOutput .= "\n";
$fixtureOutput .= "/**\n";
$fixtureOutput .= " * Autogenerated by MysqlToFixture\n";
$fixtureOutput .= " * Michael Kling - Ascendro Technologies S.R.L\n";
$fixtureOutput .= " * Date: ".date("Y-m-d H:i:s")."\n";
$fixtureOutput .= " */\n";
$fixtureOutput .= "\n";
$fixtureOutput .= "return array(\n";

$db = new mysqli($dbServer, $dbUser, $dbPass, $dbName);

if($db->connect_errno > 0){
    die('Unable to connect to database [' . $db->connect_error . ']');
}

$sql = "SELECT * FROM `$tableName`";

if(!$result = $db->query($sql)){
    die('There was an error running the query [' . $db->error . ']');
}

$i = 0;
while($row = $result->fetch_assoc()){
	$fixtureOutput .= "\t'{$tableName}_{$i}' => array(\n";
	$i++;
	
	foreach ($row as $columnName => $column) {
		$fixtureOutput .= "\t\t'{$columnName}' => '{$column}',\n";
	}
	
	$fixtureOutput .= "\t),\n";
}
$fixtureOutput .= ");\n";

echo $fixtureOutput;